// <auto-generated />
namespace MvcApplication5.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class BookModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201701061124374_BookModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
